# **EXPLORATORY DATA ANALYSIS**

In [1]:
import pandas as pd

# **SCHEDULE**

In [37]:
df_schedule = pd.read_parquet(r"C:\Users\Asus\Desktop\Formula1\data\bronze\schedule\all_seasons_schedule.parquet")
df_schedule.head()

,season,round_number,race_name,circuit_ref,race_date,race_time,fp1_date,fp2_date,fp3_date,quali_date,sprint_date,has_sprint
0,2010,1,Bahrain Grand Prix,bahrain,2010-03-14,12:00:00Z,2010-03-12,2010-03-12,2010-03-13,2010-03-13,None,False
1,2010,2,Australian Grand Prix,albert_park,2010-03-28,06:00:00Z,2010-03-26,2010-03-26,2010-03-27,2010-03-27,None,False
2,2010,3,Malaysian Grand Prix,sepang,2010-04-04,08:00:00Z,2010-04-02,2010-04-02,2010-04-03,2010-04-03,None,False
3,2010,4,Chinese Grand Prix,shanghai,2010-04-18,06:00:00Z,2010-04-16,2010-04-16,2010-04-17,2010-04-17,None,False
4,2010,5,Spanish Grand Prix,catalunya,2010-05-09,12:00:00Z,2010-05-07,2010-05-07,2010-05-08,2010-05-08,None,False

- no **PRIMARY KEY**

In [38]:
df_schedule.shape

(329, 12)

In [39]:
len(df_schedule["season"].unique())

16

In [40]:
df_schedule.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 329 entries, 0 to 328
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   season        329 non-null    int64
 1   round_number  329 non-null    int64
 2   race_name     329 non-null    object
 3   circuit_ref   329 non-null    object
 4   race_date     329 non-null    object
 5   race_time     329 non-null    object
 6   fp1_date      329 non-null    object
 7   fp2_date      311 non-null    object
 8   fp3_date      305 non-null    object
 9   quali_date    329 non-null    object
 10  sprint_date   24 non-null     object
 11  has_sprint    329 non-null    bool
dtypes: bool(1), int64(2), object(9)
memory usage: 28.7+ KB

- creating **PRIMARY KEY**
- combination of season and round_number columns is unique

In [41]:
df_schedule["schedule_ref"] = df_schedule["season"].astype(str) + "_" + df_schedule["round_number"].astype(str)

In [42]:
len(df_schedule["schedule_ref"].unique())

329

- handling race_time and race_date columns
- combining both the columns meticulously

In [43]:
df_schedule['race_datetime'] = pd.to_datetime(
    df_schedule['race_date'].astype(str) + ' ' + df_schedule['race_time'].astype(str),
    utc=True
)

In [46]:
df_schedule.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 329 entries, 0 to 328
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   season         329 non-null    int64
 1   round_number   329 non-null    int64
 2   race_name      329 non-null    object
 3   circuit_ref    329 non-null    object
 4   race_date      329 non-null    object
 5   race_time      329 non-null    object
 6   fp1_date       329 non-null    object
 7   fp2_date       311 non-null    object
 8   fp3_date       305 non-null    object
 9   quali_date     329 non-null    object
 10  sprint_date    24 non-null     object
 11  has_sprint     329 non-null    bool
 12  schedule_ref   329 non-null    object
 13  race_datetime  329 non-null    datetime64[ns, UTC]
dtypes: bool(1), datetime64[ns, UTC](1), int64(2), object(10)
memory usage: 33.9+ KB

- handling fp2_date, fp3_date and quali_date columns

In [47]:
df_schedule[df_schedule["fp2_date"].isna()]

,season,round_number,race_name,circuit_ref,race_date,race_time,fp1_date,fp2_date,fp3_date,quali_date,sprint_date,has_sprint,schedule_ref,race_datetime
262,2023,4,Azerbaijan Grand Prix,baku,2023-04-30,11:00:00Z,2023-04-28,None,None,2023-04-28,2023-04-29,True,2023_4,2023-04-30 11:00:00+00:00
267,2023,9,Austrian Grand Prix,red_bull_ring,2023-07-02,13:00:00Z,2023-06-30,None,None,2023-06-30,2023-07-01,True,2023_9,2023-07-02 13:00:00+00:00
270,2023,12,Belgian Grand Prix,spa,2023-07-30,13:00:00Z,2023-07-28,None,None,2023-07-28,2023-07-29,True,2023_12,2023-07-30 13:00:00+00:00
275,2023,17,Qatar Grand Prix,losail,2023-10-08,17:00:00Z,2023-10-06,None,None,2023-10-06,2023-10-07,True,2023_17,2023-10-08 17:00:00+00:00
276,2023,18,United States Grand Prix,americas,2023-10-22,19:00:00Z,2023-10-20,None,None,2023-10-20,2023-10-21,True,2023_18,2023-10-22 19:00:00+00:00
278,2023,20,São Paulo Grand Prix,interlagos,2023-11-05,17:00:00Z,2023-11-03,None,None,2023-11-03,2023-11-04,True,2023_20,2023-11-05 17:00:00+00:00
285,2024,5,Chinese Grand Prix,shanghai,2024-04-21,07:00:00Z,2024-04-19,None,None,2024-04-20,2024-04-20,True,2024_5,2024-04-21 07:00:00+00:00
286,2024,6,Miami Grand Prix,miami,2024-05-05,20:00:00Z,2024-05-03,None,None,2024-05-04,2024-05-04,True,2024_6,2024-05-05 20:00:00+00:00
291,2024,11,Austrian Grand Prix,red_bull_ring,2024-06-30,13:00:00Z,2024-06-28,None,None,2024-06-29,2024-06-29,True,2024_11,2024-06-30 13:00:00+00:00
299,2024,19,United States Grand Prix,americas,2024-10-20,19:00:00Z,2024-10-18,None,None,2024-10-19,2024-10-19,True,2024_19,2024-10-20 19:00:00+00:00
301,2024,21,São Paulo Grand Prix,interlagos,2024-11-03,17:00:00Z,2024-11-01,None,None,2024-11-02,2024-11-02,True,2024_21,2024-11-03 17:00:00+00:00
303,2024,23,Qatar Grand Prix,losail,2024-12-01,16:00:00Z,2024-11-29,None,None,2024-11-30,2024-11-30,True,2024_23,2024-12-01 16:00:00+00:00
306,2025,2,Chinese Grand Prix,shanghai,2025-03-23,07:00:00Z,2025-03-21,None,None,2025-03-22,2025-03-22,True,2025_2,2025-03-23 07:00:00+00:00
310,2025,6,Miami Grand Prix,miami,2025-05-04,20:00:00Z,2025-05-02,None,None,2025-05-03,2025-05-03,True,2025_6,2025-05-04 20:00:00+00:00
317,2025,13,Belgian Grand Prix,spa,2025-07-27,13:00:00Z,2025-07-25,None,None,2025-07-26,2025-07-26,True,2025_13,2025-07-27 13:00:00+00:00
323,2025,19,United States Grand Prix,americas,2025-10-19,19:00:00Z,2025-10-17,None,None,2025-10-18,2025-10-18,True,2025_19,2025-10-19 19:00:00+00:00
325,2025,21,São Paulo Grand Prix,interlagos,2025-11-09,17:00:00Z,2025-11-07,None,None,2025-11-08,2025-11-08,True,2025_21,2025-11-09 17:00:00+00:00
327,2025,23,Qatar Grand Prix,losail,2025-11-30,16:00:00Z,2025-11-28,None,None,2025-11-29,2025-11-29,True,2025_23,2025-11-30 16:00:00+00:00

In [55]:
df_schedule['fp1_date'] = pd.to_datetime(df_schedule['fp1_date'], errors='coerce')
df_schedule['fp2_date'] = pd.to_datetime(df_schedule['fp2_date'], errors='coerce')
df_schedule['fp3_date'] = pd.to_datetime(df_schedule['fp3_date'], errors='coerce')
df_schedule['quali_date'] = pd.to_datetime(df_schedule['quali_date'], errors='coerce')

- removing sprint_date, race_date and race_time column

In [53]:
df_schedule.drop(columns=["race_date", "race_time", "sprint_date"], inplace=True)

In [57]:
df_schedule = df_schedule[["schedule_ref", "season", "round_number", "race_name", "race_datetime", "circuit_ref",
                           "fp1_date", "fp2_date", "fp3_date", "quali_date", "has_sprint"]]

In [58]:
df_schedule.head()

,schedule_ref,season,round_number,race_name,race_datetime,circuit_ref,fp1_date,fp2_date,fp3_date,quali_date,has_sprint
0,2010_1,2010,1,Bahrain Grand Prix,2010-03-14 12:00:00+00:00,bahrain,2010-03-12,2010-03-12,2010-03-13,2010-03-13,False
1,2010_2,2010,2,Australian Grand Prix,2010-03-28 06:00:00+00:00,albert_park,2010-03-26,2010-03-26,2010-03-27,2010-03-27,False
2,2010_3,2010,3,Malaysian Grand Prix,2010-04-04 08:00:00+00:00,sepang,2010-04-02,2010-04-02,2010-04-03,2010-04-03,False
3,2010_4,2010,4,Chinese Grand Prix,2010-04-18 06:00:00+00:00,shanghai,2010-04-16,2010-04-16,2010-04-17,2010-04-17,False
4,2010_5,2010,5,Spanish Grand Prix,2010-05-09 12:00:00+00:00,catalunya,2010-05-07,2010-05-07,2010-05-08,2010-05-08,False

In [59]:
df_schedule.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 329 entries, 0 to 328
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   schedule_ref   329 non-null    object
 1   season         329 non-null    int64
 2   round_number   329 non-null    int64
 3   race_name      329 non-null    object
 4   race_datetime  329 non-null    datetime64[ns, UTC]
 5   circuit_ref    329 non-null    object
 6   fp1_date       329 non-null    datetime64[ns]
 7   fp2_date       311 non-null    datetime64[ns]
 8   fp3_date       305 non-null    datetime64[ns]
 9   quali_date     329 non-null    datetime64[ns]
 10  has_sprint     329 non-null    bool
dtypes: bool(1), datetime64[ns, UTC](1), datetime64[ns](4), int64(2), object(3)
memory usage: 26.2+ KB

In [61]:
df_schedule.to_parquet(r"C:\Users\Asus\Desktop\Formula1\data\silver\schedule\cleaned_schedule.parquet")