In [1]:
import pandas as pd

In [3]:
df_tele = pd.read_parquet(
    r'C:\Users\Asus\Desktop\Formula1\data\bronze\telemetry\all_seasons_telemetry.parquet')
df_tele.head(5)

,season,round_number,race_name,circuit_ref,race_date,driver_number,driver_id,lap_number,sample_count,avg_speed_kph,max_speed_kph,min_speed_kph,avg_throttle_pct,full_throttle_pct,heavy_braking_pct,drs_active_pct,avg_gear,gear_changes,avg_rpm,max_rpm
0,2018,1,Australian Grand Prix,albert_park,2018-03-25,20,kevin_magnussen,16,350,228.480,317.0,89.0,75.597,65.43,14.86,24.29,5.997,38,10625,12098
1,2018,1,Australian Grand Prix,albert_park,2018-03-25,27,hulkenberg,15,351,227.632,311.0,89.0,78.650,69.52,13.96,23.93,5.738,43,10455,11734
2,2018,1,Australian Grand Prix,albert_park,2018-03-25,3,ricciardo,13,347,231.222,311.0,90.0,77.902,70.03,12.68,22.77,5.839,39,10455,11775
3,2018,1,Australian Grand Prix,albert_park,2018-03-25,3,ricciardo,16,345,231.467,310.0,92.0,78.525,69.86,13.04,23.19,5.858,38,10451,11876
4,2018,1,Australian Grand Prix,albert_park,2018-03-25,33,max_verstappen,14,346,231.653,312.0,92.0,78.922,69.65,12.72,23.70,5.827,38,10511,12007

In [4]:
df_tele.shape

(22248, 20)

In [5]:
df_tele.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22248 entries, 0 to 22247
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   season             22248 non-null  int64
 1   round_number       22248 non-null  int64
 2   race_name          22248 non-null  object
 3   circuit_ref        22248 non-null  object
 4   race_date          22248 non-null  object
 5   driver_number      22248 non-null  object
 6   driver_id          22248 non-null  object
 7   lap_number         22248 non-null  int64
 8   sample_count       22248 non-null  int64
 9   avg_speed_kph      22248 non-null  float64
 10  max_speed_kph      22248 non-null  float64
 11  min_speed_kph      22248 non-null  float64
 12  avg_throttle_pct   22248 non-null  float64
 13  full_throttle_pct  22248 non-null  float64
 14  heavy_braking_pct  22248 non-null  float64
 15  drs_active_pct     22248 non-null  float64
 16  avg_gear           22248 non-null  float64
 17  gear_changes       22248 non-null  int64
 18  avg_rpm            22248 non-null  int64
 19  max_rpm            22248 non-null  int64
dtypes: float64(8), int64(7), object(5)
memory usage: 3.4+ MB

In [6]:
df_tele.rename(columns={"driver_id": "driver_ref"}, inplace=True)

- no **PRIMARY KEY**
- combination of season, round_number, driver_code and lap_number is **PRIMARY KEY**

In [8]:
df_tele["tele_ref"] = df_tele["season"].astype(str).str[2:4] + "_" + df_tele["round_number"].astype(str) + "_" + df_tele["driver_ref"].astype(str) + "_" + df_tele["lap_number"].astype(str)

In [9]:
df_tele["tele_ref"].head(5)

0    18_1_kevin_magnussen_16
1         18_1_hulkenberg_15
2          18_1_ricciardo_13
3          18_1_ricciardo_16
4     18_1_max_verstappen_14
Name: tele_ref, dtype: object

- handling race_date datatype

In [10]:
df_tele["race_date"] = pd.to_datetime(df_tele["race_date"])

In [23]:
df_tele.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22248 entries, 0 to 22247
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   tele_ref           22248 non-null  object
 1   season             22248 non-null  int64
 2   round_number       22248 non-null  int64
 3   race_name          22248 non-null  object
 4   circuit_ref        22248 non-null  object
 5   race_date          22248 non-null  datetime64[ns]
 6   driver_ref         22248 non-null  object
 7   driver_number      22248 non-null  int64
 8   lap_number         22248 non-null  int64
 9   sample_count       22248 non-null  int64
 10  avg_speed_kph      22248 non-null  float64
 11  max_speed_kph      22248 non-null  float64
 12  min_speed_kph      22248 non-null  float64
 13  avg_throttle_pct   22248 non-null  float64
 14  full_throttle_pct  22248 non-null  float64
 15  heavy_braking_pct  22248 non-null  float64
 16  drs_active_pct     22248 non-null  float64
 17  avg_gear           22248 non-null  float64
 18  gear_changes       22248 non-null  int64
 19  avg_rpm            22248 non-null  int64
 20  max_rpm            22248 non-null  int64
dtypes: datetime64[ns](1), float64(8), int64(8), object(4)
memory usage: 3.6+ MB

- changing datatype of driver_number

In [21]:
df_tele["driver_number"] = (df_tele["driver_number"]).astype(int)

In [22]:
df_tele.columns

Index(['tele_ref', 'season', 'round_number', 'race_name', 'circuit_ref',
       'race_date', 'driver_ref', 'driver_number', 'lap_number',
       'sample_count', 'avg_speed_kph', 'max_speed_kph', 'min_speed_kph',
       'avg_throttle_pct', 'full_throttle_pct', 'heavy_braking_pct',
       'drs_active_pct', 'avg_gear', 'gear_changes', 'avg_rpm', 'max_rpm'],
      dtype='object')

In [13]:
df_tele = df_tele[['tele_ref', 'season', 'round_number', 'race_name', 'circuit_ref', 'race_date',
       'driver_ref', 'driver_number', 'lap_number', 'sample_count', 'avg_speed_kph',
       'max_speed_kph', 'min_speed_kph', 'avg_throttle_pct',
       'full_throttle_pct', 'heavy_braking_pct', 'drs_active_pct', 'avg_gear',
       'gear_changes', 'avg_rpm', 'max_rpm']]

In [19]:
df_tele.head()

,tele_ref,season,round_number,race_name,circuit_ref,race_date,driver_ref,driver_number,lap_number,sample_count,...,max_speed_kph,min_speed_kph,avg_throttle_pct,full_throttle_pct,heavy_braking_pct,drs_active_pct,avg_gear,gear_changes,avg_rpm,max_rpm
0,18_1_kevin_magnussen_16,2018,1,Australian Grand Prix,albert_park,2018-03-25,kevin_magnussen,20,16,350,...,317.0,89.0,75.597,65.43,14.86,24.29,5.997,38,10625,12098
1,18_1_hulkenberg_15,2018,1,Australian Grand Prix,albert_park,2018-03-25,hulkenberg,27,15,351,...,311.0,89.0,78.650,69.52,13.96,23.93,5.738,43,10455,11734
2,18_1_ricciardo_13,2018,1,Australian Grand Prix,albert_park,2018-03-25,ricciardo,3,13,347,...,311.0,90.0,77.902,70.03,12.68,22.77,5.839,39,10455,11775
3,18_1_ricciardo_16,2018,1,Australian Grand Prix,albert_park,2018-03-25,ricciardo,3,16,345,...,310.0,92.0,78.525,69.86,13.04,23.19,5.858,38,10451,11876
4,18_1_max_verstappen_14,2018,1,Australian Grand Prix,albert_park,2018-03-25,max_verstappen,33,14,346,...,312.0,92.0,78.922,69.65,12.72,23.70,5.827,38,10511,12007

In [24]:
df_tele[df_tele["driver_number"]==2]

,tele_ref,season,round_number,race_name,circuit_ref,race_date,driver_ref,driver_number,lap_number,sample_count,...,max_speed_kph,min_speed_kph,avg_throttle_pct,full_throttle_pct,heavy_braking_pct,drs_active_pct,avg_gear,gear_changes,avg_rpm,max_rpm
31,18_2_vandoorne_2,2018,2,Bahrain Grand Prix,bahrain,2018-04-08,vandoorne,2,2,383,...,313.0,65.0,72.063,61.62,18.80,18.80,5.875,46,10122,12239
32,18_2_vandoorne_5,2018,2,Bahrain Grand Prix,bahrain,2018-04-08,vandoorne,2,5,383,...,311.0,67.0,72.431,61.62,17.49,18.80,5.833,47,10233,11985
33,18_2_vandoorne_8,2018,2,Bahrain Grand Prix,bahrain,2018-04-08,vandoorne,2,8,382,...,312.0,67.0,72.461,61.78,17.28,19.63,5.822,48,10240,11926
34,18_2_vandoorne_11,2018,2,Bahrain Grand Prix,bahrain,2018-04-08,vandoorne,2,11,381,...,310.0,68.0,72.507,61.94,15.49,19.16,5.806,48,10241,11867
100,18_3_vandoorne_5,2018,3,Chinese Grand Prix,shanghai,2018-04-15,vandoorne,2,5,388,...,319.0,61.0,68.000,56.96,17.53,16.49,5.621,39,10121,11638
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17934,24_13_sargeant_9,2024,13,Hungarian Grand Prix,hungaroring,2024-07-21,sargeant,2,9,286,...,316.0,91.0,65.580,54.90,24.48,15.38,5.182,44,10508,12143
17935,24_13_sargeant_12,2024,13,Hungarian Grand Prix,hungaroring,2024-07-21,sargeant,2,12,284,...,317.0,94.0,66.701,54.93,21.83,17.25,5.239,37,10516,12315
18085,24_14_sargeant_2,2024,14,Belgian Grand Prix,spa,2024-07-28,sargeant,2,2,452,...,314.0,58.0,60.241,45.58,20.80,0.00,5.372,45,10036,12410
18086,24_14_sargeant_3,2024,14,Belgian Grand Prix,spa,2024-07-28,sargeant,2,3,452,...,315.0,57.0,64.018,50.44,18.58,0.00,5.540,49,10079,12031
18087,24_14_sargeant_6,2024,14,Belgian Grand Prix,spa,2024-07-28,sargeant,2,6,432,...,318.0,58.0,63.998,50.46,17.59,0.00,5.507,45,10223,13044

In [25]:
df_tele.to_parquet(r"C:\Users\Asus\Desktop\Formula1\data\silver\telemetry\cleaned_telemetry.parquet")